name: Backend

on:
  push:
    paths:
      - 'backend/**'
      - 'proto/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'proto/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Lint proto
        run: cd proto && buf lint --error-format github-actions
      - name: Check breaking changes
        run: cd proto && buf breaking --error-format github-actions --against "https://github.com/rmrobinson/meridian.git#branch=main,subdir=proto"
      - name: Generate proto
        run: ./generate.sh
      - name: Build
        run: cd backend && go build ./...
      - name: Test
        run: cd backend && go test ./...
